# Generated by Django 5.1.5 on 2025-01-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_marks'),
        ('bursary', '0002_paymentmethod_paymenttype_payment_check_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('admission', 'Admission Fee'), ('tuition', 'Tuition Fee'), ('meals', 'Meals')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='semesterpayment',
            name='payment_types',
        ),
        migrations.RemoveField(
            model_name='semesterpayment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='semester_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='SemesterPayment',
        ),
    ]
