# Generated by Django 5.1.5 on 2025-01-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_remove_student_surname'),
        ('bursary', '0003_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissions.student'),
            preserve_default=False,
        ),
    ]
