# Generated by Django 5.1.5 on 2025-01-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_marks'),
        ('bursary', '0004_remove_payment_enrollment_payment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment'),
            preserve_default=False,
        ),
    ]
