# Generated by Django 5.1.5 on 2025-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_paymenttype_ledgerpaymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LedgerPaymentType',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
