# Generated by Django 5.1.5 on 2025-01-22 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0008_alter_payment_payment_type_delete_ledgerpaymenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.paymenttype'),
        ),
        migrations.CreateModel(
            name='PaymentTypeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type_breakdowns', to='bursary.ledger')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary.paymenttype')),
            ],
        ),
    ]
