# Generated by Django 5.1.5 on 2025-01-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0010_alter_ledger_ledger_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
