# Generated by Django 5.1.5 on 2025-01-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0014_alter_ledger_ledger_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='ledger_number',
        ),
    ]
