# Generated by Django 5.1.5 on 2025-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0015_remove_ledger_ledger_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_number',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
